const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_UPLOAD_PRESET = process.env.CLOUDINARY_UPLOAD_PRESET;

module.exports = { CLOUDINARY_CLOUD_NAME, CLOUDINARY_UPLOAD_PRESET };